apiVersion: v1
kind: Service
metadata:
  name: sample-aspnetapp
  labels:
    app: sample-aspnetapp
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: sample-aspnetapp
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sample-aspnetapp
  name: sample-aspnetapp
spec:
  # host: sample-aspnetapp-windows-container.apps.demo.aws.openshift.pub
  port:
    targetPort: 80
  to:
    kind: Service
    name: sample-aspnetapp
    weight: 100
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-aspnetapp
  name: sample-aspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-aspnetapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-aspnetapp
    spec:
      containers:
      - image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        imagePullPolicy: IfNotPresent
        name: sample-aspnetapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: windows
      tolerations:
      - key: os
        value: Windows